CREATE TABLE LEILIGHET (
    ID SERIAL PRIMARY KEY,
    NAVN VARCHAR(250),
    ADRESSE VARCHAR(250),
    POSTNR CHAR(4),
    POSTSTED VARCHAR(60)
);

CREATE TABLE INNTEKT (
    ID SERIAL PRIMARY KEY,
    LEILIGHET_ID INTEGER,
    INNTEKT_TYPE_ID INTEGER,
    BELOP INTEGER,
    AAR INTEGER,
    MND INTEGER
);

CREATE TABLE INNTEKT_TYPE (
    ID SERIAL PRIMARY KEY,
    NAVN VARCHAR(250),
    BESKRIVELSE VARCHAR(2000)
);

CREATE TABLE UTGIFT (
    ID SERIAL PRIMARY KEY,
    LEILIGHET_ID INTEGER,
    UTGIFT_TYPE_ID INTEGER,
    BELOP INTEGER,
    AAR INTEGER,
    MND INTEGER
);

CREATE TABLE UTGIFT_TYPE (
    ID SERIAL PRIMARY KEY,
    NAVN VARCHAR(250),
    BESKRIVELSE VARCHAR(2000)
);

