CREATE TABLE LEILIGHET (
    ID SERIAL PRIMARY KEY,
    NAVN VARCHAR(250),
    ADRESSE VARCHAR(250),
    POSTNR CHAR(4),
    POSTSTED VARCHAR(60)
);

CREATE TABLE INNTEKT_TYPE (
    ID SERIAL PRIMARY KEY,
    NAVN VARCHAR(250),
    BESKRIVELSE VARCHAR(2000)
);

CREATE TABLE INNTEKT (
    ID SERIAL PRIMARY KEY,
    LEILIGHET_ID INTEGER REFERENCES LEILIGHET (ID),
    INNTEKT_TYPE_ID INTEGER REFERENCES INNTEKT_TYPE (ID),
    BELOP INTEGER,
    AAR INTEGER,
    MND INTEGER,
    UNIQUE (LEILIGHET_ID, INNTEKT_TYPE_ID, AAR, MND)
);

CREATE TABLE UTGIFT_TYPE (
    ID SERIAL PRIMARY KEY,
    NAVN VARCHAR(250),
    BESKRIVELSE VARCHAR(2000)
);

CREATE TABLE UTGIFT (
    ID SERIAL PRIMARY KEY,
    LEILIGHET_ID INTEGER REFERENCES LEILIGHET (ID),
    UTGIFT_TYPE_ID INTEGER REFERENCES UTGIFT_TYPE (ID),
    BELOP INTEGER,
    AAR INTEGER,
    MND INTEGER,
    UNIQUE (LEILIGHET_ID, UTGIFT_TYPE_ID, AAR, MND)
);



