CREATE TABLE LEILIGHET (
    ID SERIAL PRIMARY KEY,
    NAVN VARCHAR(250),
    ADRESSE VARCHAR(250),
    POSTNR CHAR(4),
    POSTSTED VARCHAR(60)
);

CREATE TABLE INNTEKT_TYPE (
    ID SERIAL PRIMARY KEY,
    NAVN VARCHAR(250),
    BESKRIVELSE VARCHAR(2000)
);

CREATE TABLE INNTEKT (
    ID SERIAL PRIMARY KEY,
    LEILIGHET_ID INTEGER REFERENCES LEILIGHET (ID),
    INNTEKT_TYPE_ID INTEGER REFERENCES INNTEKT_TYPE (ID),
    BELOP INTEGER,
    AAR INTEGER,
    MND INTEGER,
    BESKRIVELSE VARCHAR(5000),
    UNIQUE (LEILIGHET_ID, INNTEKT_TYPE_ID, AAR, MND)
);

CREATE TABLE UTGIFT_TYPE (
    ID SERIAL PRIMARY KEY,
    NAVN VARCHAR(250),
    BESKRIVELSE VARCHAR(2000),
    MAANEDUAVHENGIG INTEGER
);

CREATE TABLE UTGIFT (
    ID SERIAL PRIMARY KEY,
    LEILIGHET_ID INTEGER REFERENCES LEILIGHET (ID),
    UTGIFT_TYPE_ID INTEGER REFERENCES UTGIFT_TYPE (ID),
    BELOP INTEGER,
    AAR INTEGER,
    MND INTEGER,
    BESKRIVELSE VARCHAR(5000),
    UNIQUE (LEILIGHET_ID, UTGIFT_TYPE_ID, AAR, MND)
);

CREATE TABLE SKATTEPROSENT (
    ID SERIAL PRIMARY KEY,
    AAR INTEGER,
    SKATTEPROSENT INTEGER,
    UNIQUE (AAR)
);

CREATE TABLE GRUPPERING_BASE (
    ID SERIAL PRIMARY KEY,
    GRUPPERING_NAVN VARCHAR(250),
    UNIQUE(GRUPPERING_NAVN)
);

CREATE TABLE GRUPPERTE_LEILIGHETER (
    ID SERIAL PRIMARY KEY,
    GRUPPERING_ID INTEGER REFERENCES GRUPPERING_BASE (ID),
    LEILIGHET_ID INTEGER REFERENCES LEILIGHET (ID)
);

CREATE TABLE FAKTISK_BETALT_SKATT (
    ID SERIAL PRIMARY KEY,
    GRUPPERING_ID INTEGER REFERENCES GRUPPERING_BASE (ID),
    AAR INTEGER,
    FAKTISK_SKATT_BELOP_FOR_UTLEIE INTEGER,
    FAKTISK_SKATT_BELOP_ETTER_UTLEIE INTEGER
);



