CREATE SEQUENCE LEILIGHET_SEQ;
CREATE SEQUENCE INNTEKT_SEQ;
CREATE SEQUENCE INNTEKT_TYPE_SEQ;
CREATE SEQUENCE UTGIFT_SEQ;
CREATE SEQUENCE UTGIFT_TYPE_SEQ;

CREATE TABLE "LEILIGHET" (
    ID INTEGER PRIMARY KEY,
    NAVN VARCHAR2(250),
    ADRESSE VARCHAR2(250),
    POSTNR CHAR(4),
    POSTSTED VARCHAR(60)
);

CREATE TABLE "INNTEKT" (
    ID INTEGER PRIMARY KEY,
    LEILIGHET_ID INTEGER,
    INNTEKT_TYPE_ID INTEGER,
    BELOP NUMBER,
    AAR INTEGER,
    MND INTEGER
);

CREATE TABLE "INNTEKT_TYPE" (
    ID INTEGER PRIMARY KEY,
    NAVN VARCHAR2(250),
    BESKRIVELSE VARCHAR2(2000)
);

CREATE TABLE "UTGIFT" (
    ID INTEGER PRIMARY KEY,
    LEILIGHET_ID INTEGER,
    UTGIFT_TYPE_ID INTEGER,
    BELOP NUMBER,
    AAR INTEGER,
    MND INTEGER
);

CREATE TABLE "UTGIFT_TYPE" (
    ID INTEGER PRIMARY KEY,
    NAVN VARCHAR2(250),
    BESKRIVELSE VARCHAR2(2000)
);

