INSERT INTO INNTEKT_TYPE (ID, NAVN, BESKRIVELSE) VALUES (INNTEKT_TYPE_SEQ.NEXTVAL, 'UTLEIE_INNTEKT', 'Inntekt på utleie hver måned');

INSERT INTO UTGIFT_TYPE (ID, NAVN, BESKRIVELSE) VALUES (UTGIFT_TYPE_SEQ.NEXTVAL, 'HUSLEIE', 'Fast husleie utgift hver måned');
INSERT INTO UTGIFT_TYPE (ID, NAVN, BESKRIVELSE) VALUES (UTGIFT_TYPE_SEQ.NEXTVAL, 'FESTEAVGIFT', 'Festeavgift');
INSERT INTO UTGIFT_TYPE (ID, NAVN, BESKRIVELSE) VALUES (UTGIFT_TYPE_SEQ.NEXTVAL, 'TILLEGGSUTGIFT', 'Diverse utgift');